### ISSUE TITLE
a question about wpa_supplicant

### ISSUE THREAD

**Issue by cuijianxiong** [vanhoefm/krackattacks-test-ap-ft#12]
my network.conf  is
 ctrl_interface=/var/run/wpa_supplicant
network={
	ssid="YunHeSiJi"
	key_mgmt=FT-PSK
	psk="password"
}
i have a little question
Is this SSID the SSID I'm going to attack?
and Doesn't the rest need to change?
When I execute "sudo wpa_supplicant -D nl80211 -i wlan0 -c network.conf" is wrong
such this
Successfully initialized wpa_supplicant
ctrl_iface exists and seems to be in use - cannot override it
Delete '/var/run/wpa_supplicant/wlan0' manually if it is not used anymore
Failed to initialize control interface '/var/run/wpa_supplicant'.
You may have another wpa_supplicant process already running or the file was
left by an unclean termination of wpa_supplicant in which case you will need
to manually remove this file before starting wpa_supplicant again.

and my Network card is 8187

**Comment by vanhoefm** [comment]
First learn how to connect using a normal wpa_supplicant. Then execute the script with the --help parameter and follow the instructions.

**Comment by Sc0rpi** [comment]
I find the same error in attack wifi, do you solve this problem?
