### ISSUE TITLE
Short video demonstration by using your code

### ISSUE THREAD

**Issue by ramonfontes** [vanhoefm/krackattacks-test-ap-ft#3]
I prepared a short video demonstrating how the vulnerability can be tested with Mininet-WiFi: https://www.youtube.com/watch?v=aA4notyZph0

**Comment by Mehran** [comment]
r u used another script ? i mean ./krack ?

**Comment by ramonfontes** [comment]
Hi,

No no. It was only renamed to crack.py. Its content is the same as you can
find in krack-ft-test.py.

**Comment by Mehran** [comment]
thanks why for me it freeze on here 

```
[13:44:35] Note: disable Wi-Fi in your network manager so it doesn't interfere with this script
Successfully initialized wpa_supplicant

```

**Comment by ramonfontes** [comment]
Is sta1 associated with any AP? You can check it with wpa_cli and also with iw/iwconfig. You may want to stop network manager as well.

**Comment by Mehran** [comment]
seems not associated

```
wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
```
also my wpa_cli 
```

Selected interface 'wlan0'

Interactive mode

> status
wpa_state=SCANNING
p2p_device_address=60:e3:27:07:84:91
address=60:e3:27:07:84:91
uuid=c5821608-c9a5-587e-ad60-e76a2e8b311e
<3>CTRL-EVENT-SCAN-STARTED 
<3>CTRL-EVENT-SCAN-RESULTS 
<3>WPS-AP-AVAILABLE 
<3>CTRL-EVENT-SCAN-STARTED 

```

for stop network manager also i used 
`airmon-ng check kill `
and 
`service network-manager stop`

but same ...

**Comment by ramonfontes** [comment]
I suppose you aren't using Mininet-WiFi. Am I right? If so, I think you have to prepare a real testbed and follow the instructions available at https://github.com/vanhoefm/krackattacks-test-ap-ft/blob/master/README.md#script-usage-instructions

**Comment by ramonfontes** [comment]
I prefer do not talk about physical testbeds. Mathy Vanhoef is certainly the best person to answer such question.

**Comment by vanhoefm** [comment]
Test code for a virtualized network is now included in the `hwsim-test-network` directory.
