### ISSUE TITLE
KRACK 

### ISSUE THREAD

**Issue by Atiyasharf** [vanhoefm/krackattacks-test-ap-ft#7]
sudo ./krack-ft-test.py  wlp0s20u1 wlp020u2 Aamasoom --target 64:bc:0c:7e:d4:a8

[11:08:15] Failed to determine wireless interface. Specify one using the -i parameter.

**Comment by Atiyasharf** [comment]
IV reuse detected (IV=292, seq=293). AP is vulnerable! 
result by this statement sudo ./krack-ft-test.py wpa_supplicant -D nl80211 -i wlan0 -c network.conf

**Comment by vanhoefm** [comment]
The script in the demo hasn't been released yet. The output you get is likely wrong and is just a benign retransmission.
