### ISSUE TITLE
FT-PSK Question

### ISSUE THREAD

**Issue by envoys** [vanhoefm/krackattacks-test-ap-ft#8]
So I have the TPLINK WN722N and Kali Linux. Putting the key_mgmt=FT-PSK and running wpa_supplicant, it does nothing, all it says is Successfully initialized wpa_supplicant. Running wpa_cli and it just keeps scanning. Is this because the AP isn't broadcasting using FT?

**Comment by ABAC95** [comment]
Try with key_mgmt=WPA-PSK. It worked out for me.

**Comment by fEDUntu** [comment]
Yes I can confirm it.
This is my conf file used for a WPA2-PSK (I'm using a Kali box for this demostration)

_ctrl_interface=/var/run/wpa_supplicant
update_config=1
network={
        ssid="your-ssid"
        key_mgmt=WPA-PSK
        psk="your-password"
}_

**Bonus**
I've also made a version for WPA2-PSK with hidden SSID:

_ctrl_interface=/var/run/wpa_supplicant
update_config=1
ap_scan=1
update_config=1
network={
        scan_ssid=1
        ssid="your-ssid"
        key_mgmt=WPA-PSK
        psk="your-password"
}_

**Comment by vanhoefm** [comment]
This means your AP isn't using 802.11r meaning it cannot be vulnerable. Using `key_mgmt=WPA-PSK` has no point.
