### ISSUE TITLE
line 7: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by brunotan22** [vanhoefm/krackattacks-test-ap-ft#9]
Hi,

Anyone encountered this error when running the krack-ft-test python script? Any idea how to resolve it? thanks.

line 7: syntax error near unexpected token `newline'
line 7 :'<!DOCTYPE html>'

**Comment by forte916** [comment]
You might not use a correct script. It is better to download a raw file again from the URL below.

- https://raw.githubusercontent.com/vanhoefm/krackattacks-test-ap-ft/master/krack-ft-test.py

Save downloaded file as krack-ft-test.py and run again following the usage.
